name: pipeline
run-name: ${{ github.actor }} is making a pull request
on: [pull_request]
jobs:
  job-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g @angular/cli
  job-execute:
    runs-on: ubuntu-latest
    needs: job-install
    steps:
      - run: ng serve -o --poll=2000